# basic options
title: Home
author: Shoaib Rayeen
email: shoaib.mca17.du@gmail.com
description: A wonderful site
twitter_username: shoaibrayeen
github_username: shoaibrayeen

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
