# basic options
title: Home
author: Shoaib Rayeen
email: shoaib.rayeen@yahoo.com
description: Shoaib Rayeen
twitter_username: shoaibrayeen
github_username: shoaibrayeen

# Build settings
markdown: kramdown
