# basic options
title: Home
blog: Blog
email: shoaib.mca17.du@gmail.com
description: Shoaib Rayeen
twitter_username: shoaibrayeen
github_username: shoaibrayeen

# Build settings
markdown: kramdown
theme: jekyll-theme-merlot
